create table if not exists public.leaderboard_scores (
    id bigint generated by default as identity primary key,
    session_id uuid unique,
    player_name text not null check (char_length(player_name) between 1 and 20),
    score numeric(12, 2) not null check (score >= 0),
    level integer not null check (level >= 1),
    created_at timestamptz not null default now()
);

create table if not exists public.game_sessions (
    id uuid primary key default gen_random_uuid(),
    started_at timestamptz not null default now(),
    submitted_at timestamptz,
    user_agent text
);

alter table public.leaderboard_scores enable row level security;
alter table public.game_sessions enable row level security;

revoke all on table public.leaderboard_scores from anon, authenticated;
revoke all on table public.game_sessions from anon, authenticated;
grant select on table public.leaderboard_scores to anon, authenticated;
grant select, insert, update on table public.leaderboard_scores to service_role;
grant select, insert, update on table public.game_sessions to service_role;

drop policy if exists "Anyone can view leaderboard scores." on public.leaderboard_scores;
create policy "Anyone can view leaderboard scores."
on public.leaderboard_scores
for select
to anon, authenticated
using (true);

create index if not exists leaderboard_scores_rank_idx
on public.leaderboard_scores (score desc, created_at asc);
